import { v4 as uuidv4 } from 'uuid';
import { hashPassword } from './auth.js';

const now = new Date();
const d = (offsetDays) => {
  const date = new Date(now);
  date.setDate(date.getDate() + offsetDays);
  return date.toISOString();
};

export const SEED_COMPANY_ID = 'company-seed-1';

export const seedCompanies = [
  { id: SEED_COMPANY_ID, name: 'Demo Company', createdAt: d(-90) },
];

export const seedProjects = [
  {
    id: 'proj-1',
    companyId: SEED_COMPANY_ID,
    name: 'Website Redesign',
    description: 'Complete overhaul of the company website with modern design and improved UX',
    color: '#6366f1',
    createdAt: d(-30),
  },
  {
    id: 'proj-2',
    companyId: SEED_COMPANY_ID,
    name: 'Mobile App',
    description: 'Native mobile application for iOS and Android platforms',
    color: '#f59e0b',
    createdAt: d(-25),
  },
  {
    id: 'proj-3',
    companyId: SEED_COMPANY_ID,
    name: 'Q1 Marketing Campaign',
    description: 'Multi-channel marketing campaign for Q1 product launch',
    color: '#10b981',
    createdAt: d(-20),
  },
];

export const seedDepartments = [
  { id: 'dept-1', companyId: SEED_COMPANY_ID, name: 'Engineering', color: '#6366f1', createdAt: d(-90) },
  { id: 'dept-2', companyId: SEED_COMPANY_ID, name: 'Design', color: '#f59e0b', createdAt: d(-90) },
  { id: 'dept-3', companyId: SEED_COMPANY_ID, name: 'Marketing', color: '#10b981', createdAt: d(-90) },
];

export const seedTeamMembers = [
  {
    id: 'member-1',
    companyId: SEED_COMPANY_ID,
    name: 'Alice Johnson',
    email: 'alice@example.com',
    avatarColor: '#6366f1',
    role: 'admin',
    password: hashPassword('alice123'),
    departmentId: 'dept-1',
    isDisabled: false,
    createdAt: d(-60),
  },
  {
    id: 'member-2',
    companyId: SEED_COMPANY_ID,
    name: 'Bob Smith',
    email: 'bob@example.com',
    avatarColor: '#f59e0b',
    role: 'project_manager',
    password: hashPassword('bob123'),
    departmentId: 'dept-1',
    isDisabled: false,
    createdAt: d(-55),
  },
  {
    id: 'member-3',
    companyId: SEED_COMPANY_ID,
    name: 'Carol Davis',
    email: 'carol@example.com',
    avatarColor: '#10b981',
    role: 'user',
    password: hashPassword('carol123'),
    departmentId: 'dept-2',
    isDisabled: false,
    createdAt: d(-50),
  },
  {
    id: 'member-4',
    companyId: SEED_COMPANY_ID,
    name: 'David Lee',
    email: 'david@example.com',
    avatarColor: '#ef4444',
    role: 'user',
    password: hashPassword('david123'),
    departmentId: 'dept-3',
    isDisabled: false,
    createdAt: d(-45),
  },
  {
    id: 'member-5',
    companyId: SEED_COMPANY_ID,
    name: 'Eva Martinez',
    email: 'eva@example.com',
    avatarColor: '#8b5cf6',
    role: 'project_manager',
    password: hashPassword('eva123'),
    departmentId: 'dept-3',
    isDisabled: false,
    createdAt: d(-40),
  },
];

export const seedTasks = [
  {
    id: 'task-1',
    projectId: 'proj-1',
    title: 'Design System Setup',
    description: 'Create a comprehensive design system with colors, typography, and components',
    assigneeId: 'member-1',
    startDate: d(-20),
    dueDate: d(-10),
    completionPercentage: 100,
    status: 'done',
    dependencies: [],
    priority: 'high',
    createdAt: d(-20),
  },
  {
    id: 'task-2',
    projectId: 'proj-1',
    title: 'Homepage Redesign',
    description: 'Redesign the homepage with new hero section, feature highlights, and CTA',
    assigneeId: 'member-2',
    startDate: d(-10),
    dueDate: d(5),
    completionPercentage: 75,
    status: 'in-progress',
    dependencies: ['task-1'],
    priority: 'high',
    createdAt: d(-10),
  },
  {
    id: 'task-3',
    projectId: 'proj-1',
    title: 'Mobile Responsive Layout',
    description: 'Ensure all pages are fully responsive on mobile and tablet devices',
    assigneeId: 'member-3',
    startDate: d(-5),
    dueDate: d(10),
    completionPercentage: 40,
    status: 'in-progress',
    dependencies: ['task-2'],
    priority: 'medium',
    createdAt: d(-5),
  },
  {
    id: 'task-4',
    projectId: 'proj-1',
    title: 'SEO Optimization',
    description: 'Implement meta tags, structured data, and performance improvements',
    assigneeId: 'member-1',
    startDate: d(5),
    dueDate: d(20),
    completionPercentage: 0,
    status: 'todo',
    dependencies: ['task-3'],
    priority: 'medium',
    createdAt: d(-3),
  },
  {
    id: 'task-5',
    projectId: 'proj-2',
    title: 'API Architecture',
    description: 'Design and document the REST API architecture for the mobile app',
    assigneeId: 'member-5',
    startDate: d(-15),
    dueDate: d(-5),
    completionPercentage: 100,
    status: 'done',
    dependencies: [],
    priority: 'high',
    createdAt: d(-15),
  },
  {
    id: 'task-6',
    projectId: 'proj-2',
    title: 'User Authentication',
    description: 'Implement login, registration, and password reset flows',
    assigneeId: 'member-4',
    startDate: d(-5),
    dueDate: d(8),
    completionPercentage: 60,
    status: 'in-progress',
    dependencies: ['task-5'],
    priority: 'high',
    createdAt: d(-5),
  },
  {
    id: 'task-7',
    projectId: 'proj-2',
    title: 'Push Notifications',
    description: 'Integrate push notification system for iOS and Android',
    assigneeId: 'member-2',
    startDate: d(8),
    dueDate: d(22),
    completionPercentage: 0,
    status: 'todo',
    dependencies: ['task-6'],
    priority: 'medium',
    createdAt: d(-2),
  },
  {
    id: 'task-8',
    projectId: 'proj-3',
    title: 'Campaign Strategy',
    description: 'Define target audience, messaging, and channel strategy for Q1 campaign',
    assigneeId: 'member-1',
    startDate: d(-25),
    dueDate: d(-15),
    completionPercentage: 100,
    status: 'done',
    dependencies: [],
    priority: 'high',
    createdAt: d(-25),
  },
  {
    id: 'task-9',
    projectId: 'proj-3',
    title: 'Content Creation',
    description: 'Create blog posts, social media content, and email newsletters',
    assigneeId: 'member-3',
    startDate: d(-15),
    dueDate: d(0),
    completionPercentage: 85,
    status: 'review',
    dependencies: ['task-8'],
    priority: 'medium',
    createdAt: d(-15),
  },
  {
    id: 'task-10',
    projectId: 'proj-3',
    title: 'Ad Campaign Launch',
    description: 'Launch paid advertising campaigns across Google, Facebook, and LinkedIn',
    assigneeId: 'member-5',
    startDate: d(-2),
    dueDate: d(14),
    completionPercentage: 20,
    status: 'in-progress',
    dependencies: ['task-9'],
    priority: 'high',
    createdAt: d(-2),
  },
  {
    id: 'task-11',
    projectId: 'proj-3',
    title: 'Analytics Setup',
    description: 'Configure conversion tracking, dashboards, and reporting',
    assigneeId: 'member-4',
    startDate: d(0),
    dueDate: d(10),
    completionPercentage: 10,
    status: 'in-progress',
    dependencies: ['task-8'],
    priority: 'low',
    createdAt: d(-1),
  },
  {
    id: 'task-12',
    projectId: 'proj-1',
    title: 'User Testing',
    description: 'Conduct usability testing sessions with 10 target users',
    assigneeId: 'member-2',
    startDate: d(15),
    dueDate: d(-3),
    completionPercentage: 0,
    status: 'todo',
    dependencies: ['task-3'],
    priority: 'medium',
    createdAt: d(-1),
  },
];

export const defaultColorConfig = {
  ranges: [
    { min: 0, max: 33, color: '#ef4444', label: 'Not Started' },
    { min: 34, max: 66, color: '#f59e0b', label: 'In Progress' },
    { min: 67, max: 99, color: '#3b82f6', label: 'Nearly Done' },
    { min: 100, max: 100, color: '#22c55e', label: 'Complete' },
  ],
};
